<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Game_Path>D:\SteamLibrary\steamapps\common\Nuclear Option\</Game_Path>
    <OutputPath>$(Game_Path)\BepInEx\plugins\centerVirtualJoystickWithFreelook</OutputPath>

    <AssemblyName>CenterVirtualJoystickWithFreelook</AssemblyName>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />

    <Reference Include="BepInEx" HintPath="$(Game_Path)\BepInEx\core\BepInEx.dll" Private="False" Publicize="true"/>
    <Reference Include="0Harmony" HintPath="$(Game_Path)\BepInEx\core\0Harmony.dll" Private="False" Publicize="true"/>
    <Reference Include="Assembly-CSharp" HintPath="$(Game_Path)\NuclearOption_Data\Managed\Assembly-CSharp.dll" Private="False" Publicize="true"/>
    <Reference Include="Rewired_Core" HintPath="$(Game_Path)\NuclearOption_Data\Managed\Rewired_Core.dll" Private="False" Publicize="True"/>
    <Reference Include="UnityEngine" HintPath="$(Game_Path)\NuclearOption_Data\Managed\UnityEngine.dll" Private="False" Publicize="true"/>
    <Reference Include="UnityEngine.CoreModule" HintPath="$(Game_Path)\NuclearOption_Data\Managed\UnityEngine.CoreModule.dll" Private="False" Publicize="true"/>
  </ItemGroup>
</Project>